config/routes.rb
Rails.application.routes.draw do

  devise_for :employees
  get 'feedback/enter'

  post 'feedback/create'

  get 'feedback/thanks'

  get 'feedback/show'

  devise_for :users
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/rating.rb
class Rating < ApplicationRecord
  validates_presence_of :giver, :receiver, :desc
  validates_length_of :desc, minimum: 10, maximum: 140
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # Debug
    $stderr.puts "\n--------------------------------\n"
    $stderr.puts "current_employee: #{current_employee.inspect}"
    $stderr.puts "--------------------------------\n"

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<p>You can:</p>
<ul>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if employee_signed_in? %>
      <p class="welcome">Welcome, <%= current_employee.username %>!</p>
      <p><%= link_to "Sign out", destroy_employee_session_path, method: :delete %></p>
    <% else %>
      <p>Welcome to BaseApp!</p>
      <p><%= link_to "Sign in", new_employee_session_path %></p>
    <% end %>
    <p><%= link_to "Home", root_path %></p>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>